### ISSUE TITLE
Where is example to use EventStore or Azure database

### ISSUE THREAD

**Issue by thomas-tran** [cdmdotnet/CQRS#1]
Hi,

I am really interesting in this project, where can I find example or code that implement the EventStore database or Azure database/

Thanks
Thomas.

**Comment by cdmdotnet** [comment]
We're slowly getting sample code ready. We're also getting ready to provide paid support/consulting for the framework, implementation and deployment.

For now It's a case of downloading the code samples here, using nuget to get the corresponding ninject packages swapping out the appropriate ninject modules in the global.asax (I believe) and connecting it to your azure document db.
